spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/academy_platform?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: academy123

  jpa:
    hibernate:
      # 데이터베이스 스키마 자동생성을 비활성화
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # SQL 출력 시 보기 좋게 정렬하여 출력
        show_sql: true # 콘솔에 실행되는 SQL 문을 표시하여 디버깅에 도움
    # Spring Boot에서 View 렌더링 중에 데이터베이스와의 연결이 열려 있도록 해주는 옵션
    open-in-view: false

logging:
  config: classpath:log4j2-spring.xml
  level:
    org:
      hibernate:
        sql: off
    p6spy: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

server:
  servlet:
    session:
      timeout: 2m # 세션 유지 시간 설정

