= REST Docs
academy-platform
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

== Introduction

This document describes the academy_platform API endpoints.

[[User-API]]
== User API

[[회원가입]]
== 회원가입

=== 성공적인 회원 가입

operation::join_user[snippets='http-request,request-fields,http-response,response-fields,response-body']

=== 중복된 아이디로 가입 실패

operation::join_user_fail_duplicate_id[snippets='http-request,request-fields,http-response']

[[로그인]]
== 로그인

'''
=== 로그인 성공

operation::login_user[snippets='form-parameters,http-request,http-response,response-fields']
'''

=== 잘못된 아이디 입력

operation::login_user_failed_id[snippets='form-parameters,http-request,response-fields,http-response']
'''

=== 잘못된 비밀번호 입력

operation::login_user_failed_password[snippets='form-parameters,http-request,response-fields,http-response']

[[History-API]]
== History API

[[History-조회]]
== History 조회

'''
=== 히스토리 조회 성공

operation::histories[snippets='query-parameters,http-request,http-response,response-fields']
'''

[[History-생성]]
== History 생성

'''
=== 히스토리 생성 성공

operation::create_history[snippets='http-request,request-fields,http-response,response-fields']
'''

== QaBoard API

=== QaBoard 생성

'''

=== QaBoard 생성

operation::create_board[snippets='request-fields,http-request,http-response,response-fields']
'''

=== QaBoard 여러 게시글 조회

'''

operation::search_boards[snippets='query-parameters,http-request,http-response,response-fields']
'''

=== QaBoard 게시글 단건 조회

'''
operation::search_board[snippets='query-parameters,http-request,http-response,response-fields']
'''

=== QaBoard 게시글 수정 테스트

'''
operation::update_board[snippets='request-fields,http-request,http-response,response-fields']
'''

=== QaBoard 게시글 삭제 테스트

'''
operation::delete_board[snippets='query-parameters,http-request,http-response,response-fields']
'''

== QaComment API

=== QaComment 댓글 생성 테스트

'''
operation::create_comment[snippets='request-fields,http-request,http-response,response-fields']
'''

=== QaComment 댓글 수정 테스트

'''
operation::update_comment[snippets='request-fields,http-request,http-response,response-fields']
'''

=== QaComment 댓글 삭제 테스트

'''
operation::delete_comment[snippets='query-parameters,http-request,http-response,response-fields']
'''
