# 워크플로의 이름을 정의합니다.
name: Build

# 이벤트 정의: develop 브랜치에 푸시(push)될 때 CI 작업 실행
on:
  push:
    branches:
      - feature  # develop 브랜치에 푸시가 발생할 때 실행

# jobs 섹션: 빌드 작업을 정의합니다.
jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 가상 환경에서 실행

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
